
# Plugins
# ------------------------------------------------------------------------------
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "catppuccin/tmux"


# Settings
# ------------------------------------------------------------------------------
# Better colors
set -g default-terminal "screen-256color"

# Theme
set -g @catppuccin_flavor "mocha"

# Enable mouse
set -g mouse on

# Start indexing at 1 (default zero-index)
set -g base-index 1

# Enable vi-mode (for better tmux-yank keymaps)
set-window-option -g mode-keys vi

# Gets tmux-yank working
set -g set-clipboard on


# Remaps
# ------------------------------------------------------------------------------
# Main prefix to Ctrl + Space
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Split window with | and -
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind "\\" split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

# Navigate panes (vim-ify)
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# Tmux-yank remaps
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


# Run plugin manager (keep this at the end of the file)
# ------------------------------------------------------------------------------
run "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"

